# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Amirhossein Mohammadi
tagline:          'M.A.Sc Candidate | Machine Learning Researcher'
description:      'M.A.Sc Candidate in Electrical and Computer Engineering at York University, focusing on representation learning, self-supervised learning, and world modeling.'
url:              https://amirhosseinmhd.github.io
baseurl:          ""

author:
  name:           'Amirhossein Mohammadi'
  email:          'amirmhd@yorku.ca'
  url:            https://amirhosseinmhd.github.io

# Social media
social:
  email:          amirmhd@yorku.ca
  phone:          '+1 (647) 248-2964'
  github:         https://github.com/amirhosseinmhd
  linkedin:       https://www.linkedin.com/in/amirhosseinmhd
  scholar:        https://scholar.google.com/citations?user=YOUR_ID
  twitter:        https://twitter.com/amirhosseinmhd

# Custom vars
github:
  repo:           https://github.com/amirhosseinmhd/amirhosseinmhd.github.io
